"""
Django settings for hammergym_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _get_list_setting(name, default=""):
    raw_value = config(name, default=default)
    return [item.strip() for item in raw_value.split(",") if item.strip()]


def _build_trusted_origins(hosts):
    trusted_hosts = []
    for host in hosts:
        if host in {"localhost", "127.0.0.1", "[::1]", "*"}:
            continue
        if host.startswith("."):
            trusted_hosts.append(f"https://*{host}")
        elif host.startswith("http://") or host.startswith("https://"):
            trusted_hosts.append(host)
        else:
            trusted_hosts.append(f"https://{host}")
    return trusted_hosts


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-i0nvq3fg#o&8l@ezcgvoe3tuge#pb+9g6x2e=)&x6e_lc55bi+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = _get_list_setting('ALLOWED_HOSTS', 'localhost,127.0.0.1')
CSRF_TRUSTED_ORIGINS = _get_list_setting('CSRF_TRUSTED_ORIGINS')

if not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = _build_trusted_origins(ALLOWED_HOSTS)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gym',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hammergym_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hammergym_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = config('LANGUAGE_CODE', default='ru')

TIME_ZONE = config('TIME_ZONE', default='Europe/Chisinau')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

EMAIL_BACKEND = os.getenv(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = os.getenv('DJANGO_DEFAULT_FROM_EMAIL', 'HAMMER GYM <no-reply@hammergym.com>')
ADMIN_NOTIFICATION_EMAIL = os.getenv('HAMMERGYM_ADMIN_EMAIL', 'admin@hammergym.com')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =====================================================
# SECURITY SETTINGS FOR PRODUCTION
# =====================================================
# Эти настройки автоматически включаются когда DEBUG=False
# https://docs.djangoproject.com/en/6.0/ref/settings/#security-settings

if not DEBUG:
    TRUST_PROXY_SSL_HEADER = config('TRUST_PROXY_SSL_HEADER', default=True, cast=bool)

    # HTTPS редирект (важно: на PythonAnywhere/Render SSL уже настроен)
    # Для локального тестирования с DEBUG=False можно отключить
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)

    if TRUST_PROXY_SSL_HEADER:
        # Подходит для обычного деплоя за доверенным reverse proxy.
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
        USE_X_FORWARDED_HOST = config('USE_X_FORWARDED_HOST', default=True, cast=bool)

    # Cookie безопасности
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Дополнительные защиты
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    X_FRAME_OPTIONS = 'DENY'
