# Generated by Django 6.0.2 on 2026-02-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('personal_training', 'Personal Training'), ('strength_assessment', 'Strength Assessment'), ('nutrition_consultation', 'Nutrition Consultation'), ('group_class', 'Group Class')], max_length=50)),
                ('appointment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking Appointment',
                'verbose_name_plural': 'Booking Appointments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_plan', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('elite', 'Elite')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membership Lead',
                'verbose_name_plural': 'Membership Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
